destination: _deploy
permalink: pretty
pygments: true
lsi: false
markdown: redcarpet
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile

chapters:
  - Bookmarks
  - Documentation
  - Product
  - Infrastructure
